(() => {
  'use strict';
  const ADMIN_HASH = 'e45870b5e5716bad459290561eaedf47972c65c9cb3d4f50762f46bf45e8f898';
  const digest = async (value) => Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256', new TextEncoder().encode(value)))).map((byte) => byte.toString(16).padStart(2, '0')).join('');
  const gate = async () => {
    if (sessionStorage.getItem('aiwith_admin_access') === 'granted') return true;
    const password = window.AIWITH_REQUEST_ADMIN_PASSWORD ? await window.AIWITH_REQUEST_ADMIN_PASSWORD() : window.prompt('관리자 대시보드 비밀번호를 입력하세요.');
    if (password && await digest(password) === ADMIN_HASH) { sessionStorage.setItem('aiwith_admin_access', 'granted'); return true; }
    if (password !== null) window.alert('비밀번호가 올바르지 않습니다.');
    return false;
  };
  document.documentElement.style.visibility = 'hidden';
  gate().then((allowed) => {
    if (!allowed) { location.replace('/'); return; }
    document.documentElement.style.visibility = 'visible';
    init();
  });
  function init() {
    const $ = (q) => document.querySelector(q);
    const esc = (value) => String(value ?? '').replace(/[&<>"']/g, (ch) => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
    const fmt = (value) => { try { return new Intl.DateTimeFormat('ko-KR',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value)); } catch (_) { return '-'; } };
    document.querySelectorAll('[data-admin-tab]').forEach((button) => button.addEventListener('click', () => { document.querySelectorAll('[data-admin-tab]').forEach((b) => b.classList.toggle('active', b === button)); document.querySelectorAll('.admin-view').forEach((view) => view.classList.toggle('active', view.id === 'admin-' + button.dataset.adminTab)); if (button.dataset.adminTab === 'history') loadCommits(); }));
    function renderOverview(){ const views=JSON.parse(localStorage.getItem('aiwith_pageviews')||'{}'); const drafts=JSON.parse(localStorage.getItem('aiwith_drafts')||'[]'); $('#metricTotal').textContent=views.__total||0; $('#metricDrafts').textContent=drafts.length; $('#metricUpdated').textContent=views.__last?fmt(views.__last):'-'; const rows=Object.entries(views).filter(([k])=>!k.startsWith('__')).sort((a,b)=>b[1]-a[1]); $('#pageviewList').innerHTML=rows.length?rows.map(([path,count])=>'<div class="commit-item"><b>'+esc(path)+'</b><small>'+count+'회 조회</small></div>').join(''):'<p>아직 기록된 조회가 없습니다.</p>'; }
    function renderDrafts(){ const drafts=JSON.parse(localStorage.getItem('aiwith_drafts')||'[]'); $('#draftList').innerHTML=drafts.length?drafts.map((d,i)=>'<div class="commit-item"><b>'+esc(d.type)+' · '+esc(d.title)+'</b><small>'+esc(fmt(d.updatedAt))+'</small><button class="button ghost" style="min-height:32px;margin-top:8px" data-delete-draft="'+i+'">삭제</button></div>').join(''):'<p>저장된 초안이 없습니다.</p>'; $('#metricDrafts').textContent=drafts.length; }
    function renderCardnewsDrafts(){ const drafts=JSON.parse(localStorage.getItem('aiwith_cardnews_drafts')||'[]'); $('#cardnewsDraftList').innerHTML=drafts.length?drafts.map((d,i)=>'<article class="cardnews-draft-item"><h3>'+esc(d.title)+' · 5장</h3><p>'+esc(fmt(d.updatedAt))+' · '+esc(d.summary)+'</p><div class="cardnews-draft-cards">'+(d.cards||[]).map((card,n)=>'<img src="'+esc(card.dataUrl||'')+'" alt="'+(n+1)+'장 미리보기">').join('')+'</div><div class="cardnews-draft-actions"><button class="button ghost" data-edit-cardnews="'+i+'">편집</button><button class="button ghost" data-delete-cardnews="'+i+'">삭제</button></div></article>').join(''):'<p class="cardnews-empty">등록된 카드뉴스가 없습니다.</p>'; }
    $('#editorForm')?.addEventListener('submit',(event)=>{ event.preventDefault(); const draft=Object.fromEntries(new FormData(event.currentTarget).entries()); draft.updatedAt=new Date().toISOString(); const drafts=JSON.parse(localStorage.getItem('aiwith_drafts')||'[]'); drafts.unshift(draft); localStorage.setItem('aiwith_drafts',JSON.stringify(drafts)); event.currentTarget.reset(); renderDrafts(); });
    $('#draftList')?.addEventListener('click',(event)=>{ const button=event.target.closest('[data-delete-draft]'); if(!button)return; const drafts=JSON.parse(localStorage.getItem('aiwith_drafts')||'[]'); drafts.splice(Number(button.dataset.deleteDraft),1); localStorage.setItem('aiwith_drafts',JSON.stringify(drafts)); renderDrafts(); });
    $('#exportDrafts')?.addEventListener('click',()=>{ const blob=new Blob([localStorage.getItem('aiwith_drafts')||'[]'],{type:'application/json'}); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download='aiwith-drafts.json'; a.click(); URL.revokeObjectURL(a.href); });
    const compressImage = (file) => new Promise((resolve, reject) => { const reader = new FileReader(); reader.onerror = reject; reader.onload = () => { const image = new Image(); image.onerror = reject; image.onload = () => { const max = 960; const scale = Math.min(1, max / image.width); const canvas = document.createElement('canvas'); canvas.width = Math.round(image.width * scale); canvas.height = Math.round(image.height * scale); canvas.getContext('2d').drawImage(image, 0, 0, canvas.width, canvas.height); resolve({ name:file.name, dataUrl:canvas.toDataURL('image/webp', .78) }); }; image.src = reader.result; }; reader.readAsDataURL(file); });
    let cardnewsEditingIndex = null;
    const cardInputs = ['card01','card02','card03','card04','card05'].map((name) => $('#cardnewsForm input[name="'+name+'"]'));
    const cancelCardnewsEdit = document.createElement('button'); cancelCardnewsEdit.type='button'; cancelCardnewsEdit.className='button ghost'; cancelCardnewsEdit.textContent='편집 취소'; cancelCardnewsEdit.hidden=true; $('#cardnewsForm .admin-actions').insertBefore(cancelCardnewsEdit, $('#exportCardnews'));
    const resetCardnewsForm = () => { cardnewsEditingIndex=null; $('#cardnewsForm').reset(); cardInputs.forEach((input)=>{input.required=true;}); $('#cardnewsForm button[type="submit"]').textContent='카드뉴스 저장'; cancelCardnewsEdit.hidden=true; $('#cardnewsUploadPreview').innerHTML=''; };
    const renderUploadPreview = async () => { const preview = $('#cardnewsUploadPreview'); const files = cardInputs.map((input) => input.files[0]).filter(Boolean); preview.innerHTML = files.map((file, i) => '<figure><figcaption>'+esc(file.name)+'</figcaption></figure>').join(''); const figures = [...preview.querySelectorAll('figure')]; await Promise.all(files.map(async (file, i) => { const card = await compressImage(file); figures[i].insertAdjacentHTML('afterbegin','<img src="'+esc(card.dataUrl)+'" alt="'+(i+1)+'장 미리보기">'); })); };
    cardInputs.forEach((input) => input?.addEventListener('change', () => { renderUploadPreview().catch(() => { $('#cardnewsUploadPreview').textContent = '이미지를 읽지 못했습니다. 다른 파일을 선택해 주세요.'; }); }));
    $('#cardnewsForm')?.addEventListener('submit', async (event)=>{ event.preventDefault(); const form = event.currentTarget; const files = cardInputs.map((input) => input.files[0]); const existing = cardnewsEditingIndex !== null ? (JSON.parse(localStorage.getItem('aiwith_cardnews_drafts')||'[]')[cardnewsEditingIndex]?.cards || []) : []; if (files.some((file, i) => !file && !existing[i])) { window.alert('카드 이미지 5장을 모두 선택해 주세요.'); return; } const submit = form.querySelector('button[type="submit"]'); submit.disabled = true; try { const cards = await Promise.all(files.map((file, i) => file ? compressImage(file) : Promise.resolve(existing[i]))); const draft={title:form.elements.title.value.trim(),summary:form.elements.summary.value.trim(),seo_title:form.elements.seo_title?.value.trim()||'',seo_description:form.elements.seo_description?.value.trim()||'',aeo_summary:form.elements.aeo_summary?.value.trim()||'',geo_summary:form.elements.geo_summary?.value.trim()||'',keywords:form.elements.keywords?.value.trim()||'',cards,updatedAt:new Date().toISOString()}; const drafts=JSON.parse(localStorage.getItem('aiwith_cardnews_drafts')||'[]'); if (cardnewsEditingIndex === null) drafts.unshift(draft); else drafts[cardnewsEditingIndex]=draft; localStorage.setItem('aiwith_cardnews_drafts',JSON.stringify(drafts.slice(0,30))); resetCardnewsForm(); renderCardnewsDrafts(); } catch (_) { window.alert('이미지 저장 중 오류가 발생했습니다.'); } finally { submit.disabled = false; } });
    $('#cardnewsDraftList')?.addEventListener('click',(event)=>{ const edit=event.target.closest('[data-edit-cardnews]'); if(edit){ const drafts=JSON.parse(localStorage.getItem('aiwith_cardnews_drafts')||'[]'); const draft=drafts[Number(edit.dataset.editCardnews)]; if(!draft)return; cardnewsEditingIndex=Number(edit.dataset.editCardnews); $('#cardnewsForm').elements.title.value=draft.title; $('#cardnewsForm').elements.summary.value=draft.summary; cardInputs.forEach((input)=>{input.required=false;}); $('#cardnewsForm button[type="submit"]').textContent='카드뉴스 수정 저장'; cancelCardnewsEdit.hidden=false; $('#cardnewsUploadPreview').innerHTML=(draft.cards||[]).map((card,n)=>'<figure><img src="'+esc(card.dataUrl)+'" alt="'+(n+1)+'장 미리보기"><figcaption>'+esc(card.name||((n+1)+'장'))+'</figcaption></figure>').join(''); return; } const button=event.target.closest('[data-delete-cardnews]'); if(!button)return; const drafts=JSON.parse(localStorage.getItem('aiwith_cardnews_drafts')||'[]'); drafts.splice(Number(button.dataset.deleteCardnews),1); localStorage.setItem('aiwith_cardnews_drafts',JSON.stringify(drafts)); renderCardnewsDrafts(); });
    cancelCardnewsEdit.addEventListener('click', resetCardnewsForm);
    $('#exportCardnews')?.addEventListener('click',()=>{ const blob=new Blob([localStorage.getItem('aiwith_cardnews_drafts')||'[]'],{type:'application/json'}); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download='aiwith-cardnews.json'; a.click(); URL.revokeObjectURL(a.href); });
    const summarizeCommit = (message) => {
      const text = String(message || '').toLowerCase();
      if (text.includes('cardnews editor')) return {type:'콘텐츠 관리',target:'카드뉴스 등록',summary:'카드뉴스 입력창과 공개 미리보기 구조를 일치시켰습니다.'};
      if (text.includes('original pdf')) return {type:'보안·강의',target:'웹사이트 구축 강의 전체보기',summary:'전체보기 상단의 원본 PDF 링크를 삭제했습니다.'};
      if (text.includes('lecture footer')) return {type:'사이트 구조',target:'웹사이트 구축 강의',summary:'강의 화면 하단을 공통 메뉴·정보 푸터로 통일했습니다.'};
      if (text.includes('home nav') || text.includes('square consultation')) return {type:'공통 UI',target:'전 페이지',summary:'HOME 메뉴와 정사각형 강의·워크숍 상담 플로팅 블럭을 적용했습니다.'};
      if (text.includes('content and proposal')) return {type:'메뉴·콘텐츠',target:'콘텐츠스쿨·기획서/사업계획서 스쿨',summary:'신규 스쿨 메뉴와 하부 콘텐츠 페이지를 추가했습니다.'};
      if (text.includes('ai content metadata')) return {type:'검색·AI 최적화',target:'카드뉴스·컬럼·공지 등록',summary:'SEO·AEO·GEO 입력 항목과 공개 메타정보 연계를 추가했습니다.'};
      if (text.includes('cardnews')) return {type:'콘텐츠 관리',target:'카드뉴스',summary:'카드뉴스 게시·미리보기·관리 기능을 업데이트했습니다.'};
      if (text.includes('website')) return {type:'웹사이트 스쿨',target:'웹사이트 구축 강의',summary:'웹사이트 구축 강의 화면과 운영 기능을 개선했습니다.'};
      return {type:'사이트 운영',target:'AIWITH 전체',summary:'사이트 운영 코드와 콘텐츠를 업데이트했습니다.'};
    };
    async function loadCommits(){ const root=$('#commitList'); root.innerHTML='<p>수정이력을 불러오는 중입니다.</p>'; try{ const res=await fetch('https://api.github.com/repos/mentor-k/chatgpt-sites-projectbook/commits?per_page=20',{headers:{Accept:'application/vnd.github+json'}}); if(!res.ok)throw new Error(); const commits=await res.json(); root.innerHTML=commits.map((item)=>{ const info=summarizeCommit(item.commit.message.split('\\n')[0]); return '<div class="commit-item"><div class="commit-meta"><span class="commit-type">'+esc(info.type)+'</span><span>'+esc(fmt(item.commit.author.date))+'</span><span>처리자 · '+esc(item.commit.author.name||'AIWITH 관리자')+'</span></div><b>'+esc(info.summary)+'</b><p><strong>대상 메뉴</strong> · '+esc(info.target)+'<br><strong>원문 기록</strong> · '+esc(item.commit.message.split('\\n')[0])+'</p><a class="commit-source" href="'+esc(item.html_url||'#')+'" target="_blank" rel="noreferrer">상세 기록 보기 ↗</a></div>'; }).join(''); }catch(_){ root.innerHTML='<p>수정이력을 불러오지 못했습니다. 잠시 후 다시 확인해 주세요.</p>'; } }
    $('#refreshAdmin')?.addEventListener('click',()=>{renderOverview();renderDrafts();renderCardnewsDrafts();loadCommits();});
    renderOverview(); renderDrafts(); renderCardnewsDrafts(); loadCommits();
  }
})();
