import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {validate,esc,renderColumns} from './publish-columns.mjs';
const plan=JSON.parse(fs.readFileSync(new URL('../columns/topics.json',import.meta.url),'utf8'));
const post=()=>({topicId:1,slug:plan.topics[0].slug,status:'published',title:'검증 원고',subtitle:'테스트',summary:'요약',sections:[{heading:'문제',paragraphs:['현장 문제와 실행 기준 '.repeat(85)]},{heading:'적용',paragraphs:['구체적인 교육 산출물 '.repeat(85)]}],cta:{text:'맞춤형 교육 상담'},hashtags:['a','b','c','d','e','f'],sources:[],originality:{checkedAt:'2026-10-01T22:00:00Z',queries:['제목 검색','특징 문장 검색','독자적 문장 검색'],note:'테스트 데이터'},publishedAt:'2026-10-01T23:00:00Z',updatedAt:'2026-10-01T23:00:00Z'});
test('30개 주제와 정상 원고',()=>assert.equal(validate(plan,{posts:[post()]}),true));
test('중복 주제 차단',()=>assert.throws(()=>validate(plan,{posts:[post(),post()]}),/중복 주제/));
test('미래 시각 차단',()=>assert.throws(()=>validate(plan,{posts:[{...post(),publishedAt:'2100-01-01T00:00:00Z'}]}),/시각/));
test('같은 한국 날짜 중복 차단',()=>{const second={...post(),topicId:2,slug:plan.topics[1].slug,title:'다른 제목',sections:[{heading:'실무',paragraphs:['별도의 교육 과제를 확인한다. '.repeat(90)]},{heading:'검증',paragraphs:['독자적인 실행을 검토한다. '.repeat(30)]}]};assert.throws(()=>validate(plan,{posts:[post(),second]}),/같은 날/)});
test('유사성 검수 기록 누락 차단',()=>assert.throws(()=>validate(plan,{posts:[{...post(),originality:null}]}),/유사성/));
test('HTML 및 스크립트 문자 escape',()=>assert.equal(esc('<script>"&'), '&lt;script&gt;&quot;&amp;'));
test('목록·상세·CTA·사이트맵·RSS 생성 및 재실행 중복 방지',()=>{
  const temp=fs.mkdtempSync(path.join(os.tmpdir(),'aiwith-columns-test-'));
  fs.mkdirSync(path.join(temp,'columns'));
  fs.copyFileSync(new URL('../columns/index.template',import.meta.url),path.join(temp,'columns/index.template'));
  fs.writeFileSync(path.join(temp,'columns/topics.json'),JSON.stringify(plan));
  fs.writeFileSync(path.join(temp,'columns/posts.json'),JSON.stringify({posts:[post()]}));
  fs.writeFileSync(path.join(temp,'sitemap.xml'),'<urlset><url><loc>https://aiwith.kr/workshops/</loc></url></urlset>');
  fs.writeFileSync(path.join(temp,'feed.xml'),'<rss><channel></channel></rss>');
  const result=renderColumns(temp);renderColumns(temp);
  const article=fs.readFileSync(path.join(temp,'columns',post().slug,'index.html'),'utf8');
  assert.equal(result.published,1);assert.equal(result.next,2);
  assert.match(article,/href="\/consultation\/"/);assert.match(article,/datePublished/);assert.match(article,/<h1>검증 원고<\/h1>/);
  assert.match(fs.readFileSync(path.join(temp,'columns/index.html'),'utf8'),/ai-training-outcomes/);
  const sitemap=fs.readFileSync(path.join(temp,'sitemap.xml'),'utf8');
  assert.match(sitemap,/workshops/);assert.equal(sitemap.split('ai-training-outcomes').length-1,1);
  assert.equal(fs.readFileSync(path.join(temp,'feed.xml'),'utf8').split('<item>').length-1,1);
});
