import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {validate,validateCovers,esc,renderColumns} from './publish-columns.mjs';
const plan=JSON.parse(fs.readFileSync(new URL('../columns/topics.json',import.meta.url),'utf8'));
const saved=JSON.parse(fs.readFileSync(new URL('../columns/posts.json',import.meta.url),'utf8')).posts[0];
const post=()=>({...structuredClone(saved),publishedAt:'2026-10-01T23:00:00Z',updatedAt:'2026-10-01T23:00:00Z'});
test('30개 주제와 정상 원고',()=>assert.equal(validate(plan,{posts:[post()]}),true));
test('중복 주제 차단',()=>assert.throws(()=>validate(plan,{posts:[post(),post()]}),/중복 주제/));
test('미래 시각 차단',()=>assert.throws(()=>validate(plan,{posts:[{...post(),publishedAt:'2100-01-01T00:00:00Z'}]}),/시각/));
test('같은 한국 날짜 중복 차단',()=>{const second={...post(),topicId:2,slug:plan.topics[1].slug,title:'다른 제목',sections:[{heading:'실무',paragraphs:['별도의 교육 과제를 확인한다. '.repeat(90)]},{heading:'검증',paragraphs:['독자적인 실행을 검토한다. '.repeat(30)]}]};assert.throws(()=>validate(plan,{posts:[post(),second]}),/같은 날/)});
test('유사성 검수 기록 누락 차단',()=>assert.throws(()=>validate(plan,{posts:[{...post(),originality:null}]}),/유사성/));
test('HTML 및 스크립트 문자 escape',()=>assert.equal(esc('<script>"&'), '&lt;script&gt;&quot;&amp;'));
test('이미지·키워드·질문답변 필수 및 외부 이미지 차단',()=>{
  assert.throws(()=>validate(plan,{posts:[{...post(),cover:null}]}),/대표이미지/);
  assert.throws(()=>validate(plan,{posts:[{...post(),cover:{...post().cover,src:'https://other.example/a.webp'}}]}),/대표이미지/);
  assert.throws(()=>validate(plan,{posts:[{...post(),title:'AI 교육 일반론'}]}),/타겟·문제/);
  assert.throws(()=>validate(plan,{posts:[{...post(),faq:[]}]}),/질문·답변/);
});
test('대표이미지 실제 파일 누락 및 크기 불일치 차단',()=>{
  assert.throws(()=>validateCovers({posts:[post()]},os.tmpdir()),/파일 누락/);
  assert.throws(()=>validateCovers({posts:[{...post(),cover:{...post().cover,width:1537}}]}),/크기 불일치/);
});
test('목록·상세·CTA·사이트맵·RSS 생성 및 재실행 중복 방지',()=>{
  const temp=fs.mkdtempSync(path.join(os.tmpdir(),'aiwith-columns-test-'));
  fs.mkdirSync(path.join(temp,'columns'));
  fs.mkdirSync(path.join(temp,'assets/columns'),{recursive:true});
  fs.copyFileSync(new URL('../assets/columns/ai-training-outcomes.webp',import.meta.url),path.join(temp,'assets/columns/ai-training-outcomes.webp'));
  fs.copyFileSync(new URL('../columns/index.template',import.meta.url),path.join(temp,'columns/index.template'));
  fs.writeFileSync(path.join(temp,'columns/topics.json'),JSON.stringify(plan));
  fs.writeFileSync(path.join(temp,'columns/posts.json'),JSON.stringify({posts:[post()]}));
  fs.writeFileSync(path.join(temp,'sitemap.xml'),'<urlset><url><loc>https://aiwith.kr/workshops/</loc></url></urlset>');
  fs.writeFileSync(path.join(temp,'feed.xml'),'<rss><channel></channel></rss>');
  const result=renderColumns(temp);renderColumns(temp);
  const article=fs.readFileSync(path.join(temp,'columns',post().slug,'index.html'),'utf8');
  assert.equal(result.published,1);assert.equal(result.next,2);
  assert.match(article,/href="\/consultation\/\?column=ai-training-outcomes"/);assert.match(article,/datePublished/);assert.ok(article.includes('<h1>'+esc(post().title)+'</h1>'));
  assert.match(article,/og:image" content="https:\/\/aiwith.kr\/assets\/columns\/ai-training-outcomes.webp/);
  const graph=JSON.parse(article.match(/id="aiwith-seo-jsonld" type="application\/ld\+json">([\s\S]*?)<\/script>/)[1]);
  assert.equal(graph['@graph'][0]['@type'],'BlogPosting');assert.equal(graph['@graph'][0].image.width,1536);
  assert.match(article,/이 주제의 질문과 답변/);
  const listing=fs.readFileSync(path.join(temp,'columns/index.html'),'utf8');
  assert.match(listing,/ai-training-outcomes/);
  assert.doesNotMatch(listing,/강의·워크숍 의뢰|컬럼 글쓰기|30개 컬럼 발행 계획|column-toolbar/);
  assert.match(fs.readFileSync(path.join(temp,'columns/plan/index.html'),'utf8'),/컬럼 글쓰기/);
  const sitemap=fs.readFileSync(path.join(temp,'sitemap.xml'),'utf8');
  assert.match(sitemap,/workshops/);assert.equal(sitemap.split('<loc>https://aiwith.kr/columns/ai-training-outcomes/</loc>').length-1,1);
  assert.match(sitemap,/<image:loc>https:\/\/aiwith.kr\/assets\/columns\/ai-training-outcomes.webp<\/image:loc>/);
  assert.equal(fs.readFileSync(path.join(temp,'feed.xml'),'utf8').split('<item>').length-1,1);
  assert.match(fs.readFileSync(path.join(temp,'feed.xml'),'utf8'),/enclosure.*image\/webp/);
});
